version: "3.7"

x-uffizzi:
  ingress:            # required
    service: frontend # the service that should receive https traffic
    port:    80       # the port this service listens on
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true

services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "80:80"
